version: "2.4"
services:
  mongo:
    image: mongo
    container_name: mongo
      
  login-app:
    links:
      - mongo
    image: loginapp
    container_name: login-app
    ports:
      - "8080:8080"
    environment:
      -  mongo_addr=mongo