GET http://localhost:8080 HTTP/1.1
###

POST http://localhost:8080/register HTTP/1.1
content-type: application/json

{
    "username":"username",
    "password":"password"
}
###

GET http://localhost:8080/nonce HTTP/1.1
###

POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "username":"username",
    "password":"792c892602970defcd9687ccfdd4c9a11bb842e74f521462570c40e03d9415a4",
    "nonce":"e2697d9019ca57ba441dd1d2a8259d8b"
}
###

GET http://localhost:8080/access HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwidmFsaWRVbnRpbCI6IjIwMjItMDYtMTBUMTc6MDQ6NDUuMjkwWiJ9.MzP9XRUrrcRK/EPVk3FTaBBmXFwyzKAR/3w9lXkiing=

###

POST http://localhost:8080/refresh HTTP/1.1
content-type: application/json

{
    "username":"username",
    "refreshToken":"83d8796ac379d794b6160a0814e983488929023f02d3f2bef4288b4705950c8b"
}
###

POST http://localhost:8080/revoke HTTP/1.1
content-type: application/json

{
    "jwt": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwidmFsaWRVbnRpbCI6IjIwMjItMDYtMTBUMTc6MDQ6NDUuMjkwWiJ9.MzP9XRUrrcRK/EPVk3FTaBBmXFwyzKAR/3w9lXkiing="
}